spring:
  datasource:
    username: ${POSTGRES_ROOT_USER}
    password: ${POSTGRES_ROOT_PASSWORD}
    url: jdbc:postgresql://craigmiller160.ddns.net:30019/funcoast_hi_prod
    hikari:
      connection-timeout: 5000
      idle-timeout: 5000

funcoast:
  attendance:
    first-meeting-date: 2022-10-01

logging:
  level:
    io.craigmiller160.funcoasthiattendance: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: TRACE