spring:
  datasource:
    username: ${POSTGRES_ROOT_USER}
    password: ${POSTGRES_ROOT_PASSWORD}
    url: jdbc:postgresql://craigmiller160.ddns.net:30019/funcoast_hi_prod

funcoast:
  attendance:
    first-meeting-date: 2022-10-08

logging:
  level:
    io.craigmiller160.funcoasthiattendance: DEBUG